language: php

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  slack:
    secure: PTNdRPBJpEn37XIkuWW3qYOls00FQf6XiGhi+D7+lm920pQMdk4jSVTkFtZpetLUmaB6fIC8wZp/tgJF8q1TrqbRdb+6xYaZTG8wDF3AZ/1UKWQtm8x5+VKHK/FOYW/K8gxbV4rtz3jKokZpA0iCJW5gA6v2NdkjWeNJghk9MNz/sJh6FFXbrbZMKj3jTTk1pmpuDKRxfKwsD7HQXqLad+qRRye6d0dFhfRE4MlrpcaceDRy2Ev1SDGi4eKUOlXLvkTkPpqHemcElEUXF8ITXoAhwddzG0Msq9ee482F8lMkVXGwejozkGAUw4sClTHEaa1sZ+pvrlQKQmvlmoFmrFmmpRY6jPBvq+GykuoTGvjmGNkv1D3d1279+Ff1U87WgETYinHLnDZc10ApeHpJRvofvqL/esPjdXKm0XpEhLu/iLqAD0YL1DSbTgYIQZJLbId/KVUEpdzaEOWZRf0PSlrk+mDFEhiGNsgVGnhFzBUEJyyuE5iPO+NoVDFbk3Qkkbq0IekWeqrxScY45/3rog9xZMsP+/h+5A734Aop/umxT5Zz/m66zQi5ohoHCetzU5gUtRJOi52kxFYKeTRlc6kBp2Bhl3pX0ub3Q1e+Jw1hYpklAMjFcin6Av+wXR1OG3YheMUtLGWeoQI1YPUO9xG/3XtiNjKr4Q8TBGyLOEc=

env:
  global:
    secure:

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

jobs:
  include:
    - &lint
      stage: test
      php: 7.2
      env: PHP Lint
      before_install: skip
      install: skip
      branches:
        except:
          - /^latest/
      script: find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
    - <<: *lint
      php: 7.1
    - <<: *lint
      php: 7.0
    - <<: *lint
      php: 5.6

    - &phpunit
      stage: test
      php: 7.2
      env: PHPUnit
      before_script: composer install
      script: vendor/bin/phpunit Tests/Unit/
      branches:
        except:
          - /^latest/
    - <<: *phpunit
      php: 7.1
    - <<: *phpunit
      php: 7.0
    - <<: *phpunit
      php: 5.6
      before_script: composer update --with-dependencies phpunit/phpunit
    - <<: *phpunit
      php: 7.2
      env: PHPUnit=latest
      before_script:
        - composer install
        - composer update

    - &release
      stage: release
      php: 7.2
      branches:
        except:
          - /^latest/
      before_script:
        - composer global require kherge/box:^2.7
        - composer install --no-ansi --no-interaction --no-dev --no-progress --classmap-authoritative
        - mkdir bin
      script:
        - php -d phar.readonly=0 $HOME/.composer/vendor/bin/box build
        - php bin/surf.phar --version
      deploy: &github
        provider: releases
        api_key:
          secure: aSVx7EqVUkp+RNH4suLAtN5uXW/UpkmWD1zUlzf5gjiikF0QkombwElc74T2vD1vyFDOLkL/Mm2jRPbpuZmP6ZU8Tb8rlCYAo/5015362dloJbzZwY82VxEpTBjZ3gEcJdpAKXLdaZPiILnCTkQ46uSk8uKLVIhf4b4/FnPlB4z6OjVM32ZE/F0LZxZ+B5K3wvky5PuQiUlT8EDkAbZwNi694gwA/x9HVF77Z6wopkYxXzwno0AxLGBYShtwBQ1tts3IBqNxDsv8MuYtFmVHAUkDZHiQcsThpBsPOmybavir5UlfHbnqlnHlTUIW43+aQYCsvXwVYgva9Gmc9tOHaGn2ed9QyANguXAMmFQSG+NvWcAcVyBJZ7Y5s/WGkxLMGsdj2xiS+1p0h5lDjcckdubuY/CD0+prmNQDPlvnXAn/XtYnN7UvLmhMZZ0S1oMKuCwQv8DeeJPCi/1Dn3B8YJpD3GkJdLJxY14HcVN+ztF/V+J621vqYaUfhN9bRrOqwgYZOmUDVjj4WAQ0VpoFJzCjH2IHz4+yqzHO5GrPO/Ey2+peq2jt1VavDcfc0Cdqe3FLfRQDmJexDjjR1SaR6A4NhoPBtWjOG0EMDrJpvYm6lIJ5MkmZ2st5TvkZgXtkXAjKTvCF9XIrophaBvHZFpaFnb0HhYsH7HyWQ43X8uA=
        file: bin/surf.phar
        skip_cleanup: true
        draft: true
        on:
          repo: TYPO3/Surf
          tags: true

    - <<: *release
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "t3easy"
        - git config --local user.email "3628035+t3easy@users.noreply.github.com"
        - git tag -a -m -f latest
      deploy:
        <<: *github
        name: master
        prerelease: true
        draft: true
        overwrite: true
        on:
          repo: TYPO3/Surf
          branch: master

  allow_failures:
    - php: 7.2
      env: PHPUnit=latest

#after_success:
#  - .travis/push-documentation.sh
